BEGIN;

CREATE TABLE tutors (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    telegram_user_id BIGINT NULL UNIQUE,
    telegram_chat_id BIGINT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tutor_student_assignments (
    tutor_id INTEGER NOT NULL REFERENCES tutors(id) ON DELETE RESTRICT,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tutor_id, student_id)
);

CREATE INDEX ix_tutor_student_assignments_student_id
    ON tutor_student_assignments (student_id);

COMMIT;
