BEGIN;

CREATE TABLE tutor_meetings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
    tutor_id INTEGER NOT NULL REFERENCES tutors(id) ON DELETE RESTRICT,
    status VARCHAR(16) NOT NULL
        CHECK (status IN ('SCHEDULED', 'COMPLETED', 'MISSED', 'CANCELLED')),
    scheduled_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NULL,
    cancelled_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT tutor_meetings_status_timestamps_check CHECK (
        (status = 'COMPLETED' AND completed_at IS NOT NULL
            AND completed_at >= scheduled_at AND cancelled_at IS NULL)
        OR (status = 'CANCELLED' AND completed_at IS NULL AND cancelled_at IS NOT NULL)
        OR (status IN ('SCHEDULED', 'MISSED') AND completed_at IS NULL AND cancelled_at IS NULL)
    )
);

CREATE INDEX ix_tutor_meetings_student_scheduled_at
    ON tutor_meetings (student_id, scheduled_at);

CREATE INDEX ix_tutor_meetings_tutor_scheduled_at
    ON tutor_meetings (tutor_id, scheduled_at);

COMMIT;
