BEGIN;

CREATE TABLE weekly_workflow_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_name VARCHAR(100) NOT NULL,
    execution_key VARCHAR(160) NOT NULL UNIQUE,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL,
    status VARCHAR(20) NOT NULL,
    report_payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT weekly_workflow_reports_period_order
        CHECK (period_end > period_start)
);

COMMENT ON TABLE weekly_workflow_reports IS
    'Aggregate, non-identifying weekly workflow reports for Issue #103.';
COMMENT ON COLUMN weekly_workflow_reports.report_payload IS
    'Versioned aggregate result only; never store student identities, notes, or credentials.';

COMMIT;
