BEGIN;

CREATE TABLE workflow_execution_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id UUID NOT NULL UNIQUE,
    correlation_id UUID NOT NULL,
    parent_execution_id UUID NULL,
    workflow_name VARCHAR(100) NOT NULL,
    execution_key VARCHAR(160) NULL,
    trigger_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ NULL,
    duration_ms BIGINT NULL,
    requested_count INTEGER NULL,
    processed_count INTEGER NULL,
    succeeded_count INTEGER NULL,
    failed_count INTEGER NULL,
    skipped_count INTEGER NULL,
    warning_count INTEGER NOT NULL DEFAULT 0,
    error_count INTEGER NOT NULL DEFAULT 0,
    safe_error_code VARCHAR(80) NULL,
    safe_error_summary VARCHAR(200) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT workflow_execution_logs_trigger_type
        CHECK (trigger_type IN ('direct', 'scheduler', 'workflow')),
    CONSTRAINT workflow_execution_logs_status
        CHECK (status IN ('running', 'completed', 'partial', 'failed', 'unavailable')),
    CONSTRAINT workflow_execution_logs_duration
        CHECK (duration_ms IS NULL OR duration_ms >= 0),
    CONSTRAINT workflow_execution_logs_requested_count
        CHECK (requested_count IS NULL OR requested_count >= 0),
    CONSTRAINT workflow_execution_logs_processed_count
        CHECK (processed_count IS NULL OR processed_count >= 0),
    CONSTRAINT workflow_execution_logs_succeeded_count
        CHECK (succeeded_count IS NULL OR succeeded_count >= 0),
    CONSTRAINT workflow_execution_logs_failed_count
        CHECK (failed_count IS NULL OR failed_count >= 0),
    CONSTRAINT workflow_execution_logs_skipped_count
        CHECK (skipped_count IS NULL OR skipped_count >= 0),
    CONSTRAINT workflow_execution_logs_warning_count
        CHECK (warning_count >= 0),
    CONSTRAINT workflow_execution_logs_error_count
        CHECK (error_count >= 0)
);

CREATE INDEX workflow_execution_logs_workflow_started_at_idx
    ON workflow_execution_logs (workflow_name, started_at DESC);
CREATE INDEX workflow_execution_logs_correlation_id_idx
    ON workflow_execution_logs (correlation_id);
CREATE INDEX workflow_execution_logs_execution_key_idx
    ON workflow_execution_logs (execution_key);

COMMENT ON TABLE workflow_execution_logs IS
    'Issue #108 aggregate workflow execution history. It excludes identities, payloads, messages, and secrets.';
COMMENT ON COLUMN workflow_execution_logs.safe_error_summary IS
    'Controlled generic summary only; never store raw exception text or stack traces.';

COMMIT;
