BEGIN;

-- Add only the contact fields required by tutor academic lookup workflows.
ALTER TABLE students
    ADD COLUMN IF NOT EXISTS email VARCHAR(254) NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_students_email_lower
    ON students (LOWER(email))
    WHERE email IS NOT NULL;

ALTER TABLE tutors
    ADD COLUMN IF NOT EXISTS email VARCHAR(254) NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_tutors_email_lower
    ON tutors (LOWER(email))
    WHERE email IS NOT NULL;

-- Curriculum remains the programme/semester milestone source. Courses are
-- individual searchable teaching units and therefore a separate concept.
CREATE TABLE IF NOT EXISTS courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_code VARCHAR(50) NOT NULL UNIQUE,
    course_name VARCHAR(200) NOT NULL,
    credits NUMERIC(5, 1) NOT NULL CHECK (credits > 0),
    programme_code VARCHAR(50) NULL,
    semester INTEGER NULL CHECK (semester IS NULL OR semester > 0),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_courses_name_lower
    ON courses (LOWER(course_name));

CREATE INDEX IF NOT EXISTS ix_courses_programme_code
    ON courses (programme_code);

CREATE TABLE IF NOT EXISTS course_enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE RESTRICT,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE RESTRICT,
    enrollment_status VARCHAR(20) NOT NULL DEFAULT 'ENROLLED'
        CHECK (enrollment_status IN ('ENROLLED', 'IN_PROGRESS', 'COMPLETED', 'WITHDRAWN')),
    enrolled_at DATE NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (student_id, course_id)
);

CREATE INDEX IF NOT EXISTS ix_course_enrollments_course_status
    ON course_enrollments (course_id, enrollment_status);

CREATE INDEX IF NOT EXISTS ix_course_enrollments_student_status
    ON course_enrollments (student_id, enrollment_status);

-- Reuse course_completions as the authoritative result/credit source. Existing
-- rows receive PASSED, preserving the old progress SUM semantics.
ALTER TABLE course_completions
    ADD COLUMN IF NOT EXISTS course_id INTEGER NULL
        REFERENCES courses(id) ON DELETE RESTRICT,
    ADD COLUMN IF NOT EXISTS result_status VARCHAR(20) NOT NULL DEFAULT 'PASSED',
    ADD COLUMN IF NOT EXISTS grade VARCHAR(20) NULL,
    ADD COLUMN IF NOT EXISTS completion_date DATE NULL;

ALTER TABLE course_completions
    DROP CONSTRAINT IF EXISTS ck_course_completions_result_status;

ALTER TABLE course_completions
    ADD CONSTRAINT ck_course_completions_result_status
    CHECK (result_status IN ('PASSED', 'FAILED'));

CREATE UNIQUE INDEX IF NOT EXISTS ux_course_completions_student_course
    ON course_completions (student_id, course_id)
    WHERE course_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS ix_course_completions_course_result
    ON course_completions (course_id, result_status)
    WHERE course_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS teacher_course_assignments (
    tutor_id INTEGER NOT NULL REFERENCES tutors(id) ON DELETE RESTRICT,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE RESTRICT,
    assignment_role VARCHAR(50) NOT NULL DEFAULT 'TEACHER',
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (tutor_id, course_id)
);

CREATE INDEX IF NOT EXISTS ix_teacher_course_assignments_course_id
    ON teacher_course_assignments (course_id);

COMMIT;
