BEGIN;

-- Degree programmes and cohorts are canonical academic structure entities.
-- Existing programme/programme_code and group_name columns remain available
-- as compatibility fields for current APIs and reports.
CREATE TABLE IF NOT EXISTS degree_programmes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    programme_code VARCHAR(50) NOT NULL UNIQUE,
    programme_name VARCHAR(200) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_degree_programmes_code_lower
    ON degree_programmes (LOWER(programme_code));

CREATE TABLE IF NOT EXISTS student_groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code VARCHAR(50) NOT NULL UNIQUE,
    group_name VARCHAR(200) NULL,
    programme_id INTEGER NOT NULL
        REFERENCES degree_programmes(id) ON DELETE RESTRICT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_student_groups_code_lower
    ON student_groups (LOWER(group_code));

CREATE INDEX IF NOT EXISTS ix_student_groups_programme_id
    ON student_groups (programme_id);

ALTER TABLE students
    ADD COLUMN IF NOT EXISTS group_id INTEGER NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'fk_students_group_id'
          AND conrelid = 'students'::regclass
    ) THEN
        ALTER TABLE students
            ADD CONSTRAINT fk_students_group_id
            FOREIGN KEY (group_id) REFERENCES student_groups(id)
            ON DELETE RESTRICT;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_students_group_id ON students (group_id);

CREATE TABLE IF NOT EXISTS student_group_courses (
    group_id INTEGER NOT NULL
        REFERENCES student_groups(id) ON DELETE RESTRICT,
    course_id INTEGER NOT NULL
        REFERENCES courses(id) ON DELETE RESTRICT,
    associated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (group_id, course_id)
);

CREATE INDEX IF NOT EXISTS ix_student_group_courses_course_id
    ON student_group_courses (course_id);

-- Canonicalize existing programme and group compatibility values.
INSERT INTO degree_programmes (programme_code, programme_name)
SELECT UPPER(BTRIM(student.programme_code)), MAX(student.programme)
FROM students AS student
WHERE student.programme_code IS NOT NULL
  AND BTRIM(student.programme_code) <> ''
  AND student.programme IS NOT NULL
  AND BTRIM(student.programme) <> ''
GROUP BY UPPER(BTRIM(student.programme_code))
ON CONFLICT (LOWER(programme_code)) DO UPDATE
SET programme_name = EXCLUDED.programme_name;

INSERT INTO degree_programmes (programme_code, programme_name)
VALUES ('DIN2024S', 'Business IT')
ON CONFLICT (LOWER(programme_code)) DO NOTHING;

INSERT INTO student_groups (group_code, group_name, programme_id)
SELECT source.group_name, source.group_name, programme.id
FROM (
    SELECT DISTINCT ON (LOWER(BTRIM(student.group_name)))
        UPPER(BTRIM(student.group_name)) AS group_name,
        UPPER(BTRIM(student.programme_code)) AS programme_code
    FROM students AS student
    WHERE student.group_name IS NOT NULL
      AND BTRIM(student.group_name) <> ''
      AND student.programme_code IS NOT NULL
    ORDER BY LOWER(BTRIM(student.group_name)), student.programme_code
) AS source
JOIN degree_programmes AS programme
  ON LOWER(programme.programme_code) = LOWER(source.programme_code)
ON CONFLICT (LOWER(group_code)) DO NOTHING;

INSERT INTO student_groups (group_code, group_name, programme_id)
SELECT 'DIN24', 'Digital Innovation 2024 cohort', programme.id
FROM degree_programmes AS programme
WHERE LOWER(programme.programme_code) = LOWER('DIN2024S')
ON CONFLICT (LOWER(group_code)) DO UPDATE
SET group_name = EXCLUDED.group_name,
    programme_id = EXCLUDED.programme_id;

-- Correct the historical Issue #221 demo course without breaking its FKs.
-- DII101 is the real teaching unit; DIN24 is the cohort code.
INSERT INTO courses (
    course_code, course_name, credits, programme_code, semester
)
VALUES (
    'DII101', 'Digital Innovation Foundations', 5.0, 'DIN2024S', 1
)
ON CONFLICT (course_code) DO NOTHING;

DO $$
DECLARE
    incorrect_course_id INTEGER;
    replacement_course_id INTEGER;
BEGIN
    SELECT id INTO incorrect_course_id
    FROM courses WHERE course_code = 'DIN24';

    SELECT id INTO replacement_course_id
    FROM courses WHERE course_code = 'DII101';

    IF incorrect_course_id IS NOT NULL
       AND replacement_course_id IS NOT NULL
       AND incorrect_course_id <> replacement_course_id THEN
        INSERT INTO course_enrollments (
            student_id, course_id, enrollment_status, enrolled_at
        )
        SELECT student_id, replacement_course_id, enrollment_status, enrolled_at
        FROM course_enrollments
        WHERE course_id = incorrect_course_id
        ON CONFLICT (student_id, course_id) DO NOTHING;

        DELETE FROM course_enrollments WHERE course_id = incorrect_course_id;

        -- No authority rule exists for two different completion records for
        -- the same student and teaching unit. Compare every stored field except
        -- row identity and the course identifiers/denormalized course labels.
        -- On a meaningful mismatch, abort the transaction so neither record is
        -- lost and an operator can resolve the academic record explicitly.
        IF EXISTS (
            SELECT 1
            FROM course_completions AS incorrect
            INNER JOIN course_completions AS replacement
                ON replacement.student_id = incorrect.student_id
               AND replacement.course_id = replacement_course_id
            WHERE incorrect.course_id = incorrect_course_id
              AND (
                  to_jsonb(incorrect)
                      - ARRAY['id', 'course_id', 'course_code', 'course_name']
                  IS DISTINCT FROM
                  to_jsonb(replacement)
                      - ARRAY['id', 'course_id', 'course_code', 'course_name']
              )
        ) THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                MESSAGE = 'Conflicting DIN24 and DII101 completion records require manual resolution';
        END IF;

        -- Only academically identical duplicates reach this delete. A sole
        -- obsolete record remains and is re-keyed by the following UPDATE.
        DELETE FROM course_completions AS incorrect
        WHERE incorrect.course_id = incorrect_course_id
          AND EXISTS (
              SELECT 1 FROM course_completions AS replacement
              WHERE replacement.student_id = incorrect.student_id
                AND replacement.course_id = replacement_course_id
                AND (
                    to_jsonb(incorrect)
                        - ARRAY['id', 'course_id', 'course_code', 'course_name']
                    IS NOT DISTINCT FROM
                    to_jsonb(replacement)
                        - ARRAY['id', 'course_id', 'course_code', 'course_name']
                )
          );

        UPDATE course_completions
        SET course_id = replacement_course_id
        WHERE course_id = incorrect_course_id;

        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'course_completions'
              AND column_name = 'course_code'
        ) THEN
            UPDATE course_completions
            SET course_code = 'DII101'
            WHERE course_id = replacement_course_id
              AND course_code = 'DIN24';
        END IF;

        IF EXISTS (
            SELECT 1 FROM information_schema.columns
            WHERE table_name = 'course_completions'
              AND column_name = 'course_name'
        ) THEN
            UPDATE course_completions
            SET course_name = 'Digital Innovation Foundations'
            WHERE course_id = replacement_course_id;
        END IF;

        INSERT INTO teacher_course_assignments (
            tutor_id, course_id, assignment_role
        )
        SELECT tutor_id, replacement_course_id, assignment_role
        FROM teacher_course_assignments
        WHERE course_id = incorrect_course_id
        ON CONFLICT (tutor_id, course_id) DO NOTHING;

        DELETE FROM teacher_course_assignments
        WHERE course_id = incorrect_course_id;

        DELETE FROM courses WHERE id = incorrect_course_id;
    END IF;
END $$;

-- The deterministic demo cohort contains multiple students and real courses.
UPDATE students
SET group_name = 'DIN24', programme_code = 'DIN2024S'
WHERE student_number IN ('DEMO22101', 'DEMO22102', 'DEMO22103');

UPDATE students AS student
SET group_id = student_group.id
FROM student_groups AS student_group
WHERE LOWER(student_group.group_code) = LOWER(student.group_name)
  AND student.group_id IS DISTINCT FROM student_group.id;

INSERT INTO student_group_courses (group_id, course_id)
SELECT student_group.id, course.id
FROM student_groups AS student_group
JOIN courses AS course
  ON course.course_code IN ('DII101', 'DBS24', 'WEB24')
WHERE LOWER(student_group.group_code) = LOWER('DIN24')
ON CONFLICT (group_id, course_id) DO NOTHING;

COMMIT;
